l_simp_chinese:
  #搾乳廠
  pm_preg_women: "孕婦產乳"
  pm_encourage_drug: "催產藥"
  pm_no_penismilking: "無搾精"
  pm_penismilking: "搾精"
  pm_aphrodisiac_penismilking: "春藥催產"
  pm_nature_production: "自然生產"
  pm_additive_drug: "添加春藥"
  pm_handjob: "手工生產"
  pm_breedmount: "繁殖架固定"
  pm_automatic_milkingmachine: "自動化搾乳機"
  pm_private_owner: "奴隸主所有制"
  pm_no_entertainment_milking: "無娛樂設施"
  pm_entertainment_milking: "娛樂服務"
  pmg_base_lacation_milking: "乳汁生產"
  pmg_penis_milking: "精液生產"
  pmg_additive: "藥物增產"
  pmg_automatic_milking: "自動化生產"
  pmg_milking_entertainment: "娛樂設施"
  #妓院
  pm_cheap_streetwalker: "廉價流鶯"
  pm_experienced_streetwalker: "熟練流鶯"
  pm_skilled_whore: "老練娼妓"
  pm_no_gloryhole: "不提供尋歡洞"
  pm_gloryhole: "提供尋歡洞"
  pmg_brothel_service: "妓院服務"
  pmg_gloryhole: "尋歡洞"
  pmg_brothel_madam: "妓院管理"
  #情色出版商
  pm_pornnovel: "色情小說"
  pm_pornmovie: "色情影片"
  pm_no_advertisepage: "無廣告"
  pm_advertisepage: "廣告頁"
  pmg_advertisepage: "廣告"
  pmg_publication_owner: "所有權"
  pmg_pornpublication: "色情出版品"
  #淫能發電廠
  pm_orgasm_power: "高潮能源"
  pm_semen_power: "精液能源"
  pm_only_worker: "純勞工維護"
  pm_professional_maintenance: "專業維護"
  pm_hamodgovernment: "國營企業"
  pmg_hornypowergene: "發電方式"
  pmg_powerplant_maintenance: "發電廠維護"
  pmg_powerplant_management: "發電廠管理"
  #性玩具製造廠
  pm_handmade_sextoy: "手工製作"
  pm_machine_production_sextoy: "機器生產"
  pm_rubber_onahole: "橡膠自慰套"
  pm_no_chastitycage: "無貞操鎖"
  pm_chastitycage: "貞操鎖"
  pm_no_dxsextoy: "僅普通自慰玩具"
  pm_less_dxsextoy: "小規模生產"
  pm_mass_dxsextoy: "大規模生產"
  pm_no_milkingmachine: "無搾汁機"
  pm_milkingmachine: "搾汁機"
  pmg_sex_toy: "自慰玩具"
  pmg_chastitycage: "貞操鎖"
  pmg_dxsextoy: "豪華性玩具"
  pmg_milkingmachine: "搾汁機"
  pmg_owner_sextoy: "管理方式"
  #淫水採集廠
  pm_tradition_orgasm: "傳統高潮"
	pm_support_orgasm: "玩具輔助"
  pm_no_facility_entertainment: "純生產部門"
	pm_facility_entertainment: "提供娛樂服務"
  pmg_fluid_collection: "淫水採集"
  pmg_facility_entertainment: "娛樂服務"
  pmg_facility_owner: "所有者"
  #學院
  pm_masturbation_education: "自慰教學"
  pm_sex_education: "性交演練"
  pm_breed_academy: "生育學院"
  pm_trap_academia: "男娘管理"
  pmg_base_breed_academy: "基礎學科"
  pmg_breed_academy_academia: "學者類型"
  #製藥工廠
  pmg_aphrodisiac_production: "生產規模"
  pm_labproduction_pharmaceutical: "實驗室生產"
  pm_industrialproduction_pharmaceutical: "工業化生產"
  pm_automaticproduction_pharmaceutical: "自動化生產"
  #避孕用品
  pmg_condom_production: "保險套生產"
  pmg_contraceptiongoods_factory_owner: "所有者"
  pm_tradition_condom: "手工生產"
  pm_rubber_condom: "橡膠原料"
  pm_automatic_condom_production: "自動化生產"